// <auto-generated />
namespace JobPool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SignUpRecruiter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SignUpRecruiter));
        
        string IMigrationMetadata.Id
        {
            get { return "201906290901534_SignUpRecruiter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
